[tool.poetry]
name = "fino2py"
version = "0.1.0"
description = "A package to help researchers and clinicians work with data produced by the finopress finometer"
authors = ["Kev O'Malley"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.1"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
